### ISSUE TITLE
Populate File System Docker ne fonctionne pas pour /etc/hosts /etc/hostname

### ISSUE THREAD

**Issue by Sda79** [Manu-31/yane#4]
**Le problème :** 
La commande que j'utilise pour copier des fichers depuis la machine hôte vers un container docker est la suivante : 
```bash
$ docker cp ./src <containerHostName>:/dest
```
Elle marche parfaitement sauf pour certains fichiers notamment `/etc/hosts` ou `/etc/hostname`.
On l'observe clairement si ou utilise la configuration suivante : 
```yaml
network :
  name: netnsetc
  version: 1.0
  hosts:
    -
      name: rt-a
      mode: docker
      files: rt-a/etc:/
    -
      name: rt-b
      mode: namespace
      files: rt-b/etc:/

  links :
    - rt-a:v0:192.168.10.1/24!rt-b:v0:192.168.10.2/24

  consoles :
    - all

  dumpif :
    - all
```
Le souci est que docker utilise ses propres `/etc/hostname`  `/etc/hosts`. On peut changer ces paramètres dans un container docker mais pas avec de la copie de fichiers car docker ne le permet pas.

**Solutions envisageable :**
* Modifier la syntaxe de `yane.yml` notament pour `/etc/hostname` : 
```yaml
hosts:
    -
      name: rt-a
      mode: docker
      hostname: virtual-a
      files: rt-a/etc:/
```
Cette solution serait très simple à mettre en place pour l'hostname. A voir pour hosts.
* Copier le fichier `hosts` et/ou `hostname` sur le `/tmp` du container docker puis d'écraser /etc/... depuis l'intérieur du container docker...
